config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'categories#index' 

  resources :artworks do
    resources :loans
    member do
      get 'send_request' => 'artworks#send_request'
    end
  end

  post 'artworks/:id/favorite' => 'artworks#favorite'

  authenticate :users do
    resources :artworks, :only => [:new, :create, :edit, :update, :destroy]
  end

  resources :categories, :only => :show
  resources :artworks, :only => [ :show ] do
    get 'sort/:sort_attribute', :to => "artworks#sort", :as => :sort, :on => :collection
  end

end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  belongs_to :category
  belongs_to :user

  has_attached_file :photo, styles: {
  					thumb: '100x100>',
  					square: '200x200#',
  					medium: '300x300>'
  					}
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
  # scope :title_order, => 'artworks.title ASC'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :artworks
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :artwork
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :favorites
  has_many :artworks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  include Pundit
end

app/controllers/artwork_controller.rb
class ArtworkController < ApplicationController
 
 def new
    @artwork = Artwork.new
  end

  def create
    @artwork = current_user.artworks.build safe_create_params
    @artwork.category = Category.find_or_create_by(name: params[:category])

    if @artwork.save
      flash[:notice] = "Artwork added."
      redirect_to artwork_path(@artwork)
    else
      flash.now[:alert] = @artwork.errors.first
      render 'new'
    end
  end

  def show
    @artwork = Artwork.find params[:id]
  end

end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
 
 def new
    @artwork = Artwork.new
  end

  def create
    @artwork = current_user.artworks.build safe_create_params
    @artwork.category = Category.find_or_create_by(name: params[:category])

    if @artwork.save
      flash[:notice] = "Artwork added."
      redirect_to artwork_path(@artwork)
    else
      flash.now[:alert] = @artwork.errors.first
      render 'new'
    end
  end

  def favorite
    artwork = Artwork.find(params[:id])
    current_user.artworks << artwork
  end

  def send_request
    @user = current_user
    @artwork = Artwork.find(params[:id])
    if user_signed_in?
      UserMailer.request_art(current_user, @artwork).deliver
      flash[:notice] = "Megan has been notified of your interest. She will email you as soon as possible with purchasing details."
      redirect_to @artwork
    end
  end

  def show
    @artwork = Artwork.find params[:id]
  end

  def edit
    @artwork = Artwork.find(params[:id])
  end

  def update
    @artwork = Artwork.find(params[:id])
    authorize @artwork
    if @artwork.update(safe_create_params)
      flash[:notice] = "The artwork has been updated."
      redirect_to artwork_path(@artwork)
    else
      flash.now[:error] = @artwork.errors.messages.first.join(" ")
      render 'edit'
    end
  end

  def destroy
    @artwork = Artwork.find(params[:id])
    @artwork.destroy
    flash[:notice] = "'#{@artwork.title}' has been deleted."
    redirect_to root_path
  end


def safe_create_params
    params.require(:artwork).permit(:photo, :title, :medium, :dimensions, :category, :price, :order_print)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.where(id: params[:id]).includes(:artworks).first  
    @artworks = if params[:sort] == 'price'
                  @category.artworks.order(:price)
                elsif params[:sort] == 'title'
                  @category.artworks.order(:title)
                else
                  @category.artworks.order(:created_at).reverse
                end
  end

def index
    @categories = Category.order(:name).all
    @artwork = Artwork.new
end

  def update
  end

  def edit
  end

  def new
  end

  def create
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artwork_helper.rb
module ArtworkHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/artworks/_form.html.erb
<%= form_for @artwork do |f| %>
  <fieldset>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag :category %>
      <%= text_field_tag :category, nil, class: 'form-control' %>
      
    </div>
    <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, step: 0.01, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :dimensions %>
      <%= f.text_field :dimensions, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :order_print %>
      <%= f.text_field :order_print, class: 'form-control' %>
    </div>
    <div class="form-group">
    <%= f.label :photo %>
    <%= f.file_field :photo, class: 'form-control'%>
    </div>
  </fieldset>

  <%= f.submit @artwork.new_record? ? "Create" : "Update" %>
<% end %>

app/views/artworks/edit.html.erb
<h1>Update a Work of Art</h1>

<div class="container">
<% if flash[:error] %>
  <p><%= flash[:error] %></p>
<% end %>

<%= render 'form' %>

<%= link_to "Cancel", root_path %>
</div>

app/views/artworks/new.html.erb
<h1>Add a Work of Art</h1>

<div class="container">
 <% if flash[:error] %>
  <p><%= flash[:error] %></p>
<% end %>

<%= render 'form' %>

<%= link_to "Cancel", root_path %>
</div>

app/views/artworks/show.html.erb
<h1><%= @artwork.title %></h1>
<%= image_tag @artwork.photo.url %>
<p>Medium: <%= @artwork.medium %><br>
Dimensions: <%= @artwork.dimensions %><br>
<a href="<%= @artwork.order_print %>" target="_blank">Order a Print</a><br>
Price: $<%= @artwork.price %><br>
<strong><a href="mailto:meg@mcoyle.com?subject=Interested%20in%20Buying%20<%= @artwork.title %>&amp;body=Hi%20Megan,%0D%0A%0D%0AI'm%20interested%20in%20buying:%0D%0A%0D%0ATitle:%20<%= @artwork.title %>%0D%0ADimensions:%20<%= @artwork.dimensions%>%0D%0APrice:%20$<%= @artwork.price %>">Buy the Original Work of Art</a></strong><br>

</p>

<div class="small-button"><%= link_to "Back to #{@artwork.category.name.capitalize} Gallery", @artwork.category, class: "btn btn-default" %></div>

<% if policy(@artwork).update? %>
<div class="editing">
<p><%= link_to "Edit Artwork", edit_artwork_path(@artwork) %> | <%= link_to "Delete Artwork", artwork_path(@artwork), method: 'delete' %></p>
</div>
<% end %>

app/views/categories/edit.html.erb
<h1>Galleries#edit</h1>
<p>Find me in app/views/galleries/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Artwork Available for Sale</h1>
<% if policy(@artwork).create? %>
<p><%= link_to "Add a Work of Art", new_artwork_path %></p>
<% end %>
<p>Navigate to a gallery to view artwork that is available for sale.</p>
<section>
<div class="gallery">
  <% @categories.each do |category| %>
    <div class="gallery-item">
      <h3><%= link_to category.name.capitalize, category_path(category) %></h3>
      <% if category.name == "animals" %>
      	<%= link_to (image_tag "/images/available-animals.jpg"), category_path(category) %>
      	<% elsif category.name == "people" %>
      	<%= link_to (image_tag "/images/available-people.jpg"), category_path(category) %>
      	<% elsif category.name == "places" %>
      	<%= link_to (image_tag "/images/available-places.jpg"), category_path(category) %>
      	<% elsif category.name == "things" %>
      	<%= link_to (image_tag "/images/available-stilllife.jpg"), category_path(category) %>
      	<% end %>
    </div>
  <% end %>
</div>
</section>

app/views/categories/new.html.erb
<h1>Galleries#new</h1>
<p>Find me in app/views/galleries/new.html.erb</p>

app/views/categories/show.html.erb
<h1><%= @category.name.capitalize %></h1>

<p>Sort by: <%= link_to "Price", "?sort=price" %> | <%= link_to "Title", "?sort=title" %> | <%= link_to "Recently Added", "?sort=created_at" %></p>

<div class="gallery">
  <% @artworks.each do |artwork| %>
    <div class="gallery-item">
    	<%= link_to (image_tag artwork.photo.url(:square)), artwork_path(artwork) %>
    	<p><%= link_to artwork.title, artwork_path(artwork), class: 'artwork_link' %></p>
    	<p>$<%= artwork.price %></p>
    </div>
    
  <% end %>

</div>

<div class="med-button"><%= link_to "Back to Galleries", root_path, class: "btn btn-default" %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width">
  <title>Megan Coyle: Collage Artist and Illustrator - Gallery Application</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
  		<a href="http://www.mcoyle.com"><img class="logo" src="/assets/megan-coyle-collage-artist.jpg"/></a>
  	</div>
  	<nav class="navbar navbar-default">
      <ul class="nav navbar-nav">
      	<li><%= link_to "Artwork for Sale", root_path %></li>

        <% if user_signed_in? %>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
</div>

<div class="container">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
</div>
    <footer>
     <div class="col-md-3">
     	<ul>
     		<li>About</li>
     		<li><a href="http://www.mcoyle.com/galleries/">Artwork</a></li>
     		<li><a href="http://www.mcoyle.com/about/artist-bio/">Artist Bio</a></li>
     		<li><a href="http://www.mcoyle.com/about/artist-statement/">Artist Statement</a></li>
     		<li><a href="http://www.mcoyle.com/faq/">FAQs</a></li>
     	</ul>
     </div>
     <div class="col-md-3">
     	<ul>
     		<li>More Info</li>
     		<li><a href="http://www.mcoyle.com/index.php?page_id=59">Exhibits</a></li>
     		<li><a href="http://www.mcoyle.com/index.php?page_id=110">Press</a></li>
     		<li><a href="http://www.mcoyle.com/learn/process/">Process</a></li>
     		<li><a href="http://www.mcoyle.com/contact/">Contact</a></li>
     	</ul>
     </div>
     <div class="col-md-3">
     	<ul>
     		<li>Store</li>
     		<li><a href="http://www.mcoyle.com/store/available-work/">Original Art</a></li>
     		<li><a href="http://www.mcoyle.com/store/prints/">Prints</a></li>
     		<li><a href="http://www.mcoyle.com/commission-work/">Custom Art</a></li>
     		<li><a href="http://www.mcoyle.com/store/">All Merchandise</a></li>
     	</ul>
     </div>
     <div class="col-md-3">
     	<ul>
     		<li class="blogsections">Blog Sections</li>
     		<li><a href="http://www.mcoyle.com/category/in-the-studio-original-collage-art/">In the Studio: Original Collage Art</a></li>
     		<li><a href="http://www.mcoyle.com/category/the-adventures-of-bosty/">The Adventures of Bosty</a></li>
     		<li><a href="http://www.mcoyle.com/category/a-day-in-the-life-of-an-artist/">A Day in the Life of an Artist</a></li>
     		<li><a href="http://www.mcoyle.com/category/blabberart-interviews-and-talks/">Interviews and Talks</a></li>
     	</ul>
     </div>
     
     <div id="socialmedia">
     	  <a href="http://www.facebook.com/Megan.Coyle.Art" target="_blank"><img src="/assets/facebook2.png" width="35" height="35"></a>
        <a href="https://twitter.com/megancoyle" target="_blank"><img src="/assets/twitter.png" width="35" height="35"></a>
        <a href="https://www.etsy.com/shop/meganacoyle" target="_blank"><img src="/assets/etsy.png" width="35" height="35"></a>
        <a href="http://instagram.com/megancoyleartist" target="_blank"><img src="/assets/instagram.png" width="35" height="35"></a>
        <a href="http://megancoyleart.tumblr.com/" target="_blank"><img src="/assets/tumblr.png" width="35" height="35"></a>
        <a href="http://www.youtube.com/user/megancoyleart" target="_blank"><img src="/assets/youtube.png" width="35" height="35"></a>
		    <a href="http://www.flickr.com/photos/megancoyle/" target="_blank"><img src="/assets/flickr-2.png" width="35" height="35"></a>
	   </div>
      <div id="site-copyright">Copyright &copy; <%= Time.now.year %> by Megan Coyle. All Rights reserved.
      </div>
    </footer>
	</body>
</html>